#!/usr/bin/env bun

// Reads src/landing/tokens.css and generates src/landing/tokens-css.ts
// This allows the CSS to be imported as a string on any platform (Bun, CF Workers)

const css = await Bun.file("src/landing/tokens.css").text();

const escaped = css
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$/g, "\\$");

const output = `// Auto-generated by scripts/generate-tokens.ts — do not edit
export const TOKENS_CSS = \`${escaped}\`;
`;

await Bun.write("src/landing/tokens-css.ts", output);
console.log("✓ src/landing/tokens-css.ts generated");
